const {test}=require('node:test');const assert=require('node:assert/strict');const {dateKey,shiftDay,streak,initialState,validateState}=require('../core.cjs');
test('calendar math crosses month and year boundaries',()=>{assert.equal(shiftDay('2026-01-01',-1),'2025-12-31');assert.equal(shiftDay('2024-03-01',-1),'2024-02-29');assert.equal(dateKey(new Date(2026,0,2)),'2026-01-02');});
test('streak includes tiny steps and allows today to remain incomplete',()=>{const h={logs:{'2026-09-18':'tiny','2026-09-17':'full'}};assert.equal(streak(h,'2026-09-19'),2);h.logs['2026-09-19']='full';assert.equal(streak(h,'2026-09-19'),3);assert.equal(streak(h,'2026-09-21'),0);});
test('backup validation rejects invalid structures',()=>{assert.equal(validateState(initialState()).version,1);assert.throws(()=>validateState({}));const s=initialState();s.model='../../bad';assert.throws(()=>validateState(s));});
test('OpenAI coaching is fixed to GPT-5 Mini',()=>{const s=initialState();assert.equal(s.model,'gpt-5-mini');s.model='gpt-5';assert.equal(validateState(s).model,'gpt-5-mini');});
test('legacy provider settings remain readable before migration',()=>{const s=initialState();s.provider='openrouter';s.model='meta-llama/llama-3.3-70b-instruct:free';s.baseUrl='https://openrouter.ai/api/v1';assert.equal(validateState(s).provider,'openrouter');});
test('reflection backups retain entries and reject malformed or oversized data',()=>{const s=initialState();s.journal={'2026-09-20':{mood:'good',note:'I showed up.'}};assert.equal(validateState(s).journal['2026-09-20'].note,'I showed up.');s.journal['2026-09-20'].mood='invalid';assert.throws(()=>validateState(s),/reflection/);s.journal['2026-09-20']={mood:'good',note:'x'.repeat(4001)};assert.throws(()=>validateState(s),/reflection/);});
test('theme persists and validates light and dark modes',()=>{const s=initialState();assert.equal(validateState(s).theme,'dark');s.theme='light';assert.equal(validateState(s).theme,'light');s.theme='neon';assert.throws(()=>validateState(s),/theme/);});
test('soundEnabled persists and validates boolean preference',()=>{const s=initialState();assert.equal(validateState(s).soundEnabled,true);s.soundEnabled=false;assert.equal(validateState(s).soundEnabled,false);s.soundEnabled='yes';assert.throws(()=>validateState(s),/sound/);});
