const {chromium}=require('C:/Users/ltgre/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path');const {initialState,dateKey}=require('../core.cjs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.emulateMedia({reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));const seed=initialState();seed.theme='light';seed.habits=[{id:'existing',created:dateKey(),logs:{[dateKey()]:'tiny'},name:'Read daily',cue:'I make coffee',tiny:'read one page',reward:'Tea',time:'Morning',icon:'📖'}];await page.addInitScript(seed=>{window.desktop={load:async()=>({state:JSON.parse(localStorage.getItem('testState')||JSON.stringify(seed)),hasKey:true,isTest:true}),save:async s=>{if(window.failSave)throw Error('disk full');localStorage.setItem('testState',JSON.stringify(s));return true;},hasKey:async()=>true,chat:async(messages,attachment)=>{window.lastAttachment=attachment;return window.mockReply||'What routine could this follow?';}};},seed);await page.goto('file:///'+path.resolve('index.html').replaceAll('\\','/'));await page.locator('.habit').waitFor();assert.equal(await page.locator('.chat-welcome,.welcome-prompts,[data-welcome]').count(),0);assert.equal(await page.locator('.suggestions button').count(),4);assert.equal(await page.locator('#chat-model,.model-picker').count(),0);assert.equal(await page.evaluate(()=>state.model),'gpt-5-mini');
await page.locator('[data-view=journal]').click();assert.deepEqual(await page.locator('.mood > span').allTextContents(),['😞','😌','😐','🙂','😁']);await page.locator('[data-view=today]').click();await page.locator('.habit').waitFor();

await page.locator('#chat-input').fill('Help me read');await page.locator('#send').click();await page.getByText('What routine could this follow?').waitFor();
await page.locator('#chat-input').fill('Unsent reading draft');await page.locator('#chat-context').click();await page.locator('[data-context=existing]').click();
const first=await page.evaluate(()=>state.activeChatId);await page.getByRole('button',{name:'New chat',exact:true}).click();assert.equal(await page.locator('#chat-input').inputValue(),'');assert.equal(await page.locator('#habit-attachment').isVisible(),false);assert.equal(await page.evaluate(()=>state.chats.length),2);
await page.locator('#chat-input').fill('Help me exercise');await page.locator('#send').click();await page.getByText('What routine could this follow?').waitFor();const second=await page.evaluate(()=>state.activeChatId);
await page.locator('#chat-history').click();await page.screenshot({path:'test-results/chat-history.png'});await page.locator('[data-chat="'+first+'"]').click();assert.equal(await page.locator('#chat-input').inputValue(),'Unsent reading draft');assert.equal(await page.locator('#habit-attachment').isVisible(),true);assert.equal(await page.evaluate(()=>state.messages[0].text),'Help me read');
await page.reload();await page.locator('#habit-attachment').waitFor();assert.equal(await page.locator('#chat-input').inputValue(),'Unsent reading draft');
await page.locator('#chat-history').click();await page.locator('[data-delete-chat="'+second+'"]').click();await page.locator('#cancel-chat-delete').click();assert.equal(await page.locator('[data-chat]').count(),2);await page.locator('[data-delete-chat="'+second+'"]').click();await page.locator('#confirm-chat-delete').click();assert.equal(await page.evaluate(()=>state.chats.length),1);assert.equal(await page.evaluate(()=>state.activeChatId),first);
await page.locator('#settings').click();await page.locator('#setting-key').waitFor();assert.equal(await page.locator('#setting-provider,#setting-model,#setting-baseurl').count(),0);await page.getByText('Enter your own OpenAI API key.',{exact:false}).waitFor();await page.getByText('GPT-5 Mini',{exact:false}).first().waitFor();await page.screenshot({path:'test-results/settings-simplified.png'});await page.locator('[name=enterToSend]').uncheck();await page.locator('[name=includeHabitContext]').uncheck();await page.locator('[name=coachOnStartup]').check();await page.locator('[name=soundEnabled]').uncheck();await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.locator('#chat-input').fill('Two');await page.locator('#chat-input').press('Enter');await page.locator('#chat-input').pressSequentially('lines');assert.equal(await page.locator('#chat-input').inputValue(),'Two\nlines');
await page.reload();await page.locator('.habit').waitFor();assert.equal(await page.evaluate(()=>state.enterToSend),false);assert.equal(await page.evaluate(()=>state.includeHabitContext),false);assert.equal(await page.evaluate(()=>state.coachOnStartup),true);
await page.locator('#chat-history').click();await page.locator('[data-delete-chat]').click();await page.locator('#confirm-chat-delete').click();assert.equal(await page.evaluate(()=>state.chats.length),1);assert.equal(await page.evaluate(()=>state.messages.length),0);assert.equal(await page.evaluate(()=>state.habits.length),1);
await page.locator('#settings').click();await page.locator('#setting-key').click();assert.equal(await page.locator('#modal').evaluate(el=>el.open),true);await page.mouse.click(20,20);assert.equal(await page.locator('#modal').evaluate(el=>el.open),false);await page.locator('#add-habit').click();await page.mouse.click(20,20);assert.equal(await page.locator('#modal').evaluate(el=>el.open),false);await page.locator('#chat-history').click();await page.mouse.click(20,20);assert.equal(await page.locator('#modal').evaluate(el=>el.open),false);assert.deepEqual(errors,[]);console.log('PASS: mood faces, GPT-5 Mini settings, new/switch/delete chats, cancel deletion, draft and mention persistence, settings persistence, Enter behavior, preserved habits.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
